INSERT INTO sbd.seleksi_masuk
VALUES (1, 'SNMPTN', 'SELEKSI NASIONAL MAHASISWA PERGURUAN TINGGI NEGERI'),
       (2, 'SBMPTN', 'SELEKSI BERSAMA MAHASISWA PERGURUAN TINGGI NEGERI');

SELECT *
FROM sbd.seleksi_masuk;