CREATE TABLE SBD.MERCHANT
(
    ID           VARCHAR(36)  NOT NULL
        CONSTRAINT PK_MERCHANT_ID PRIMARY KEY,
    ADDRESS_ID   VARCHAR(36)  NOT NULL,
    NAME         VARCHAR(100) NOT NULL,
    EMAIL        VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(15)  NOT NULL
);

ALTER TABLE SBD.MERCHANT
    ADD CONSTRAINT FK_MERCHANT_ADDRESS_ID FOREIGN KEY (ADDRESS_ID) REFERENCES SBD.ADDRESS (ID)
    ADD CONSTRAINT UQ_MERCHANT_EMAIL UNIQUE (EMAIL)
    ADD CONSTRAINT UQ_MERCHANT_PHONE_NUMBER UNIQUE (PHONE_NUMBER)
    ADD CONSTRAINT UQ_MERCHANT_NAME UNIQUE (NAME);

ALTER TABLE SBD.MERCHANT
    DROP CONSTRAINT UQ_MERCHANT_NAME;