CREATE TABLE SBD.PREPARING_STAFF
(
    ID            VARCHAR(36) NOT NULL
        CONSTRAINT PK_PREPARING_STAFF_ID PRIMARY KEY,
    DEPARTMENT_ID VARCHAR(36) NOT NULL
);

ALTER TABLE SBD.PREPARING_STAFF
    ADD CONSTRAINT FK_PREPARING_STAFF_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES SBD.DEPARTMENT (ID)
    ADD CONSTRAINT UQ_PREPARING_STAFF_MERCHANT_ID UNIQUE (DEPARTMENT_ID);

ALTER TABLE SBD.PREPARING_STAFF
    DROP CONSTRAINT UQ_PREPARING_STAFF_MERCHANT_ID;