CREATE TABLE SBD.PRODUCT
(
    ID          VARCHAR(36)  NOT NULL
        CONSTRAINT PK_STAFF_ID PRIMARY KEY,
    MERCHANT_ID VARCHAR(36)  NOT NULL,
    NAME        VARCHAR(100) NOT NULL
);

ALTER TABLE SBD.PRODUCT
    ADD CONSTRAINT FK_PRODUCT_MERCHANT_ID FOREIGN KEY (MERCHANT_ID) REFERENCES SBD.MERCHANT (ID)
    ADD CONSTRAINT UQ_PRODUCT_NAME UNIQUE (NAME);

ALTER TABLE SBD.PRODUCT
    DROP CONSTRAINT UQ_PRODUCT_NAME;