CREATE SCHEMA SBD;

drop table

CREATE TABLE SBD.ADDRESS
(
    ID           VARCHAR(36)  NOT NULL
        CONSTRAINT PK_ADDRESS_ID PRIMARY KEY,
    STREET       VARCHAR(255) NOT NULL,
    POSTAL_CODE  VARCHAR(45)  NOT NULL,
    RT           VARCHAR(45)  NOT NULL,
    RW           VARCHAR(45)  NOT NULL,
    WARD         VARCHAR(100) NOT NULL,
    SUB_DISTRICT VARCHAR(100) NOT NULL,
    CITY         VARCHAR(100) NOT NULL,
    PROVINCE     VARCHAR(100) NOT NULL
);

ALTER TABLE ADDRESS
    ADD CONSTRAINT UQ_ADDRESS_STREET UNIQUE (STREET);

ALTER TABLE ADDRESS
    DROP CONSTRAINT UQ_ADDRESS_STREET;
