CREATE TABLE SBD.COOKING_STAFF
(
    ID            VARCHAR(36) NOT NULL
        CONSTRAINT PK_COOKING_STAFF_ID PRIMARY KEY,
    DEPARTMENT_ID VARCHAR(36) NOT NULL
);

ALTER TABLE SBD.COOKING_STAFF
    ADD CONSTRAINT FK_COOKING_STAFF_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES SBD.DEPARTMENT (ID)

    ADD CONSTRAINT UQ_COOKING_STAFF_MERCHANT_ID UNIQUE (DEPARTMENT_ID);

ALTER TABLE SBD.COOKING_STAFF
    DROP CONSTRAINT UQ_COOKING_STAFF_MERCHANT_ID;